# Generated by Django 3.1.2 on 2020-10-31 18:12

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Autoencoders', 'Deep Belief Net'), ('Deep Belief Net', 'Deep Belief Net'), ('Convolutional Neural Networks', 'Convolutional Neural Networks'), ('Recurrent Neural Networks', 'Recurrent Neural Networks'), ('Reinforcement Learning', 'Reinforcement Learning'), ('Natural language processing', 'Natural language processing'), ('Recommendation systems++', 'Recommendation systems'), ('Bioinformatics', 'Bioinformatics'), ('Mobile advertising', 'Mobile advertising'), ('Financial fraud detection', 'Financial fraud detection')], default='HTML', max_length=100)),
                ('number', models.PositiveIntegerField(default=1, verbose_name='iin chandomie?')),
                ('title', models.CharField(default='', max_length=100)),
                ('summary', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('links', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
