# Generated by Django 3.1.2 on 2020-10-06 16:33

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('HTML5', 'HTML'), ('Bootstrap4', 'Bootstrap4'), ('Css3', 'Css3'), ('Js', 'js'), ('Kotlin', 'Kotlin'), ('Java', 'java'), ('C++', 'C++'), ('Perl', 'Perl'), ('C-Sharp', 'C-Sharp'), ('Python', 'Python'), ('GraphQL', 'GraphQL'), ('REST', 'REST'), ('PostgreSQL', 'PostgreSQL'), ('MySQL', 'MySQL'), ('SQLServer', 'SQLServer'), ('linux', 'linux'), ('git', 'git'), ('docker', 'docker')], default='HTML', max_length=100)),
                ('number', models.PositiveIntegerField(default=1, verbose_name='iin chandomie?')),
                ('title', models.CharField(default='', max_length=100)),
                ('summary', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('links', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
